export {
  default as RecordingObject,
  RECORDING_UNIVERSAL_IDENTIFIER,
  NAME_FIELD_ID,
  BOT_ID_FIELD_ID,
  DATE_FIELD_ID,
  DURATION_FIELD_ID,
  TRANSCRIPT_FIELD_ID,
  MEETING_URL_FIELD_ID,
  MP4_URL_FIELD_ID,
  PLATFORM_FIELD_ID,
  STATUS_FIELD_ID,
} from './recording';
